version: '3.8'  # Use a suitable version for your needs

services:
  finfindr-server:
    image: finfindr-server  # Use your custom image name
    container_name: finfindr-server
    ports:
      - "8080:8080"  # Map port 5200 inside the container to port 8000 on the host
