version: '3.8'

services:
  finfindr-server:
    image: finfindr-server
    container_name: finfindr-server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - finfindr-network

  postgres:
    image: postgres
    container_name: finfindrdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: finfindrdb
    ports:
      - "5432:5432"
    networks:
      - finfindr-network

networks:
  finfindr-network:
    driver: bridge
