version: '3.8' 

services:
  finfindr-server:
    image: finfindr-server
    container_name: finfindr-server
    ports:
      - "8080:8080"
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db
    environment:
      - ORACLE_PWD=admin12345
    ports:
      - "1521:1521"  # Oracle database port
      - "5500:5500"  # Oracle EM Express port
    volumes:
      - oracle-data:/opt/oracle/oradata  # Persistent data storage

volumes:
  oracle-data: