version: '3.8' 

services:
  finfindr-server:
    image: finfindr-server
    container_name: finfindr-server
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    container_name: finfindr-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: finfindrdb
    network_mode: host


