version: '3.8' 

services:
  finfindr-server:
    image: finfindr-server
    container_name: finfindr-server
    ports:
      - "8080:8080"
  oracle-db:
    image: oracleinanutshell/oracle-xe-11g
    container_name: oracle-xe-11g
    platform: linux/amd64
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle
    restart: unless-stopped

volumes:
  oracle-data: